language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "pypy"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libdiscid0
install: pip install -q --use-mirrors discid musicbrainzngs
script: python setup.py test
branches:
  except:
    - v1
